// Generated by https://quicktype.io


export interface ICumpleaniosSocios {
  numero:          string;
  nombre:          string;
  fechanacimiento: string;
  direccion:       string;
  telefonos:       string;
  agencia:         string;
  asesor:          string;
  edad:            number;
  dias:            number;
}
