// Generated by https://quicktype.io

export interface ISituacioCrediticia {
  nombrecliente?:     string;
  numerocliente?:     number |string;
  identificacion?:    string;
  telefonos?:         string;
  operacion?:         string;
  tipoprestamo?:      string;
  nombreagencia?:     string;
  fechaadjudicacion?: string;
  asesororiginal?:    string;
  asesorcambio?:    string;
}
