export enum Role {
    ADMIN = "001",
    GERENTE = "002",
    ASISTENTE_CREDITO = "015",
    ADMINISTRATIVO = "058",
    JEFE_OPERATIVO = "006" ,
    ASISTENTE_DE_CAPTACIONES = "024",
    JEFE_NEGOCIOS = "036",
    ASESOR_NEGOCIOS = "014",
    ASESOR_CAPTACIONES = "022",
    JEFE_AGENCIA = "51",
    GESTOR_DPF = "062",
    GESTOR_CREDITO = "016",
    OFICIAL_CUMPLIMIENTO = "025",
    PROMOTOR_PRODUCTOS_SERVICIOS = "065",
    COORDINADOR_TECNOLOGIA = "045",
    ASISTENTE_TECNOLOGIA = "029"
}
